### ISSUE TITLE
Failed to resolve dependencies

### ISSUE THREAD

**Issue by jeff-h** [trilemma-dev/Blessed#11]
First off, sorry if this is user error rather than specifically a Blessed/SecureXPC question:

I'm attempting to debug my app in Catalina as my helper is crashing both there and in Big Sur (it runs fine in Monterey). To this end I've installed macOS Catalina 10.15.4 on a partition and set up Xcode 12.4, which is the latest available for 10.15. I've also installed and selected the Swift 5.6.1 toolchain.

Despite selecting the 5.6.1 toolchain, I get "Failed to resolve dependencies": "because every version of Blessed contains incompatible tools version and root depends on Blessed 0.3.0..<1.0.0, version solving failed."

Am I missing something? Has anyone else successfully used Blessed/SecureXPC in Xcode running on Catalina?

**Comment by jakaplan** [comment]
I think (but am far from certain) the issue you're running into is that Blessed has a `swift-tools-version` of 5.5, and Xcode 12 does not support this version. While you've installed Swift 5.6.1, I don't think that's sufficient unless that also installed corresponding tools:
> The Swift tools version declares the version of the PackageDescription library, the minimum version of the Swift tools and Swift language compatibility version to process the manifest, and the required minimum version of the Swift tools to use the Swift package.

From https://developer.apple.com/documentation/swift_packages/package

---

It's certainly a hack, but to unblock yourself for debugging purposes you ought to be able to just copy and paste the files `Blessed` framework files directly into your own project.

**Comment by jeff-h** [comment]
Thanks for your help. I do remain somewhat convinced you *should* be able to upgrade the tools by installing a new version of Swift (and thus getting access to an upgraded toolchain). However, I still haven't been able to get that to work.

I did get your hack idea to work (thanks!) but ended up deciding to start fresh in Big Sur as the helper is crashing there also, and Big Sur can run an Xcode that has Swift 5.5 so everything was just a bit easier to get running.

Still haven't found the source of my helper crash though 😡 but that's another topic altogether ha.
